#!/bin/sh 
# 
# script to bring up the tun device in QEMU in bridged mode 
# first parameter is name of tap device (e.g. tap0)
#
# some constants specific to the local host - change to suit your host
#
#
# First take bond0 down, then bring it up with IP address 0.0.0.0 
#
/sbin/ifdown bond0
/sbin/ifconfig bond0 0.0.0.0 promisc up
#
# Bring up the tap device (name specified as first argument, by QEMU)
#
/usr/sbin/openvpn --mktun --dev $1 --user `id -un`
/sbin/ifconfig $1 0.0.0.0 promisc up
#
# create the bridge between bond0 and the tap device
#
/usr/sbin/brctl addbr br0
/usr/sbin/brctl addif br0 bond0
/usr/sbin/brctl addif br0 $1
# 
# only a single bridge so loops are not possible, turn off spanning tree protocol
#
/usr/sbin/brctl stp br0 off 
# 
# Bring up the bridge with DHCP 
#
#dhclient br0
