#!/bin/sh

from=$1; shift

set -e

if ! svn=$(command -v svn); then
	svn=svnlite
fi
$svn up

revs=$(echo $* | sed -e 's/r//g' | tr ' ' '\n' | sort -nu)

for i in $revs; do
	$svn merge -c $i $from .
done
$(dirname $0)/mfc_log $from $revs > commit

$svn status

echo
cat commit
